export const USER_SIGNUP_STARTED = 'USER_SIGNUP_STARTED';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';
export const MESSAGE_SET = 'MESSAGE_SET';
export const ERROR_SET = 'ERROR_SET';
export const MESSAGE_CLEAR_ALL = 'MESSAGE_CLEAR_ALL';
