export const USER_AUTH_STARTED = 'USER_AUTH_STARTED';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILED = 'USER_AUTH_FAILED';
export const MESSAGE_SET = 'MESSAGE_SET';
export const ERROR_SET = 'ERROR_SET';
export const MESSAGE_CLEAR_ALL = 'MESSAGE_CLEAR_ALL';
